apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: siddhiprocesses.siddhi.io
spec:
  group: siddhi.io
  names:
    kind: SiddhiProcess
    listKind: SiddhiProcessList
    plural: siddhiprocesses
    singular: siddhiprocess
    shortNames:
      - sp
      - sps
      - siddhi
      - siddhis
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
  additionalPrinterColumns:
    - name: Type
      type: string
      description: Deployment type
      JSONPath: .status.type
    - name: Status
      type: string
      description: Status
      JSONPath: .status.status
    - name: Ready
      type: string
      description: Ready deployments
      JSONPath: .status.ready
    - name: Age
      type: date
      description: Age
      JSONPath: .metadata.creationTimestamp
