---
# This config map used to parse configurations to the siddhi operator.
apiVersion: v1
kind: ConfigMap
metadata:
  name: siddhi-operator-config
data:
  siddhiRunnerHome: /home/siddhi_user/siddhi-runner/
  siddhiRunnerImage: siddhiio/siddhi-runner-alpine:5.1.0-m1
  autoIngressCreation: "true"
  # ingressTLS: siddhi-tls
---

# Deployment of the siddhi operator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siddhi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: siddhi-operator
  template:
    metadata:
      labels:
        name: siddhi-operator
    spec:
      serviceAccountName: siddhi-operator
      containers:
        - name: siddhi-operator
          image: siddhiio/siddhi-operator:0.2.0-m1
          command:
          - siddhi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: siddhi-operator
            - name: OPERATOR_VERSION
              value: 0.2.0-m1
            - name: OPERATOR_CONFIGMAP
              value: siddhi-operator-config

---

# Deployment of the siddhi parser
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  name: siddhi-parser
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: siddhi-parser
      version: 0.2.0-m1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: siddhi-parser
        version: 0.2.0-m1
    spec:
      containers:
      - image: siddhiio/siddhi-parser:0.2.0-m1
        imagePullPolicy: IfNotPresent
        name: siddhirunner-msf4j
        ports:
        - containerPort: 9090
          name: port
          protocol: TCP

---

# Service of the siddhi parser
apiVersion: v1
kind: Service
metadata:
  name: siddhi-parser
spec:
  ports:
  - name: msf4j
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    name: siddhi-parser
    version: 0.2.0-m1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

---