apiVersion: apps/v1
kind: Deployment
metadata:
  name: siddhi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: siddhi-operator
  template:
    metadata:
      labels:
        name: siddhi-operator
    spec:
      serviceAccountName: siddhi-operator
      containers:
        - name: siddhi-operator
          image: docker.io/siddhiio/siddhi-operator:0.1.1
          command:
          - siddhi-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: siddhi-operator
            - name: OPERATOR_VERSION
              value: 0.1.0
            - name: SIDDHI_RUNNER_IMAGE
              value: siddhiio/siddhi-runner-alpine
            - name: SIDDHI_RUNNER_IMAGE_TAG
              value: 0.1.0
            - name: SIDDHI_RUNNER_IMAGE_SECRET
              value: null
            - name: SIDDHI_RUNNER_HOME
              value: /home/siddhi_user/siddhi-runner-0.1.0/
            - name: SIDDHI_PARSER_URL
              value: http://siddhi-parser/parse
            - name: AUTO_INGRESS_CREATION
              value: "true"


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  name: siddhi-parser
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: siddhi-parser
      version: 1.0.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: siddhi-parser
        version: 1.0.0
    spec:
      containers:
      - image: siddhiio/siddhi-parser-alpine:0.1.1
        imagePullPolicy: IfNotPresent
        name: siddhirunner-msf4j
        ports:
        - containerPort: 9090
          name: port
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: siddhi-parser
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: msf4j
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    name: siddhi-parser
    version: 1.0.0
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
